# Check that the changelog is updated for all changes.
#
# This is only run for PRs.

on:
  pull_request:
    # opened, reopened, synchronize are the default types for pull_request.
    # labeled, unlabeled ensure this check is also run if a label is added or removed.
    types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  contents: read
  pull-requests: read

name: Changelog

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Check that changelog updated
        uses: dangoslen/changelog-enforcer@204e7d3ef26579f4cd0fd759c57032656fdf23c7 # v3
        with:
          changeLogPath: CHANGELOG.md
          skipLabels: 'needs-changelog, skip-changelog'
          missingUpdateErrorMessage: 'Please add a changelog entry in the CHANGELOG.md file.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
